---
abstract: "munge your \"has\" (works with Moo, Moose and Mouse)"
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
  Test::Requires: 0.06
  Types::Standard: 0.006
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.007, CPAN::Meta::Converter version 2.120921'
keywords: []
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-MungeHas
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
provides:
  MooseX::MungeHas:
    file: lib/MooseX/MungeHas.pm
    version: 0.004
requires:
  Eval::TypeTiny: 0.006
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooseX-MungeHas/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-MungeHas
  homepage: https://metacpan.org/release/MooseX-MungeHas
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moosex-mungehas
version: 0.004
x_contributors:
  - 'Andrew Rodland (ARODLAND) <arodland@cpan.org>'
x_provides_scripts: {}
